apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vootingappkustomization
  namespace: fluxcd
resources:
  - namespace.yaml
  - db-pvc.yaml
  - redis-pvc.yaml
  - db-deployment.yaml
  - redis-deployment.yaml
  - db-service.yaml
  - redis-service.yaml
  - worker-deployment.yaml
  - vote-deployment.yaml
  - vote-service.yaml
  - result-deployment.yaml
  - result-service.yaml


  