---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vooting-app-sot
  namespace: k8s
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/LinuxNerdBTW/vooting-app-sot.git
