---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vooting-app-sot
  namespace: k8s
spec:
  interval: 30s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: vooting-app-sot
